import { Geist, Geist_Mono, Poppins, Lato, Quicksand, Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/navbar";
import Footer from "./components/layouts/footer";
import { CartProvider } from "@/context/cartcontext";
import { Toaster } from "react-hot-toast";
import { FilterProvider } from "@/context/filtercontext";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope",
})

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-quicksand",
})

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
  variable: "--font-lato",
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Fruit Ecommerce Website",
  description: "Generated by create next app",
  icons: { icon: "/websitetabicon.png" }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${lato.variable} ${quicksand.variable} ${manrope.variable} antialiased`}
      >
        <Navbar></Navbar>
        <CartProvider>
          <FilterProvider>
          <Toaster position="top-right" reverseOrder={false} />
          {children}
          </FilterProvider>
        </CartProvider>
        <Footer></Footer>
      </body>
    </html>
  );
}
